#version: "3.9"
############################
# VOLUMENS
############################
volumes:
  zabbix-postgresdb:
  zabbix-server:
  zabbix-snmptraps:
  zabbix_dashboard_config:
  zabbix_certificados:
############################
# NETWORKS
############################
networks:
  zabbix_network:
    driver: bridge
############################
# SERVICES
############################
services:
  ###########################
  # POSTGRES
  ###########################
  zabbix-postgres-bd:
    networks:
      - zabbix_network
    image: postgres:17.6
    container_name: zabbix-postgres-bd
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    volumes:
      - zabbix-postgresdb:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
  ###########################
  # ZABBIX SERVER
  ###########################
  zabbix-server-pgsql:
    networks:
      - zabbix_network
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server-pgsql
    restart: unless-stopped
    depends_on:
      zabbix-postgres-bd:
        condition: service_healthy
    environment:
      - DB_SERVER_HOST=${ZBX_DB_IP}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ZBX_ENABLE_SNMP_TRAPS=${ZBX_ENABLE_SNMP_TRAPS}
      - TZ=${TZ}
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server:/var/lib/zabbix
      - ./alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./externalscripts:/usr/lib/zabbix/externalscripts:ro
      - zabbix-snmptraps:/var/lib/zabbix/snmptraps
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/10051' || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 300s
  ###########################
  # ZABBIX WEB (NGINX)
  ###########################
  zabbix-dashboard:
    networks:
      - zabbix_network
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-dashboard
    restart: unless-stopped
    depends_on:
      zabbix-postgres-bd:
        condition: service_healthy
      zabbix-server-pgsql:
        condition: service_healthy
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          curl -sf -X POST http://localhost:8080/api_jsonrpc.php \
          -H "Content-Type: application/json" \
          -d '{"jsonrpc":"2.0","method":"apiinfo.version","params":{},"id":1}' || exit 1
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_IP}
      - DB_SERVER_HOST=${ZBX_DB_IP}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PHP_TZ=${PHP_TZ}
    ports:
      - "${PORT_HTTPS}:8443"
      - "${PORT_HTTP}:8080"
    volumes:
      - zabbix_certificados:/etc/ssl/nginx:ro
      - zabbix_dashboard_config:/usr/share/zabbix
    #security_opt:
    #  - seccomp=unconfined
  ##########################
  # ZABBIX AGENT 2
  ###########################
  zabbix-agent2:
    networks:
      - zabbix_network
    build:
        context: ./agent2/
        dockerfile: Dockerfile
    image: simovilab/zabbix-agent2:ubuntu-7.4.3
    container_name: zabbix-agent2
    hostname: ${LOCAL_HOST_NAME}
    restart: unless-stopped
    privileged: true
    group_add:
     - "$DOCKER_GID"
    depends_on:
      zabbix-postgres-bd:
        condition: service_healthy
      zabbix-server-pgsql:
        condition: service_healthy
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_IP}
      - ZBX_ACTIVE_ALLOW=${ZBX_ACTIVE_ALLOW}
      - ZBX_METADATA=${ZBX_METADATA}
      - ZBX_HOSTINTERFACE=${HOST_DNS}
      - TZ=${TZ}
    volumes:
      - /proc:/proc:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/user_scripts/:/var/lib/zabbix/user_scripts/:ro
      - ./agent2/${ZBX_AGENT_CONFIG_FILE}:/etc/zabbix/zabbix_agent2.d/${ZBX_AGENT_CONFIG_FILE}:ro
      - ./agent2/${AGENT_SUDOERS_FILE}:/etc/sudoers.d/${AGENT_SUDOERS_FILE}:ro
  ##########################
  # INIT CONTAINER
  ###########################
  zabbix-init:
    networks:
      - zabbix_network
    image: alpine/curl:latest
    env_file: .env
    volumes:
      - ./${SCRIPT_POST_INSTALL}:/init.sh:ro
      - ./psk/zabbix_agentd.psk:/zabbix_agentd.psk:ro
      - ./templates/${AGENT_TEMPLATE_FILE}:/${AGENT_TEMPLATE_FILE}:ro
    entrypoint: ["sh", "-c", "apk add --no-cache bash jq && exec bash /init.sh"]
    depends_on:
      zabbix-dashboard:
        condition: service_healthy
      zabbix-server-pgsql:
        condition: service_healthy
    restart: "no"
