############################
# NETWORKS
############################
networks:
  databus_network:
    external: true
############################
# SERVICES
############################
services:
  ##########################
  # ZABBIX AGENT 2
  ###########################
  zabbix-agent2:
    networks:
      - databus_network
    build:
        context: .
        dockerfile: Dockerfile
    image: simovilab/zabbix-agent2:ubuntu-7.4.3
    container_name: remote-zabbix-agent2
    hostname: ${REMOTE_AGENT_HOSTNAME}
    restart: unless-stopped
    privileged: true
    ports:
      - "${ZBX_PORTS}"
    group_add:
      - "${DOCKER_GID}"
    environment:
      - TZ=${TZ}
      - ZBX_SERVER_HOST=${SERVER_FQDN}
      - ZBX_HOSTNAME=${REMOTE_AGENT_HOSTNAME}
      - ZBX_METADATA=${ZBX_METADATA}
      - ZBX_HOSTINTERFACE=${AGENT_FQDN}
      - ZBX_ACTIVE_ALLOW=${ZBX_ACTIVE_ALLOW}
      - ZBX_REFRESH_ACTIVE_CHECKS=${ZBX_REFRESH_ACTIVE_CHECKS}
      - ZBX_TLSCONNECT=${ZBX_TLSCONNECT}         
      - ZBX_TLSACCEPT=${ZBX_TLSACCEPT}         
      - ZBX_TLSPSKIDENTITY=${ZBX_TLSPSKIDENTITY} 
      - ZBX_TLSPSKFILE=${ZBX_TLSPSKFILE}  
    volumes:
      - /proc:/proc:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../psk/${ZBX_TLSPSKFILENAME}:${ZBX_TLSPSKFILE}:ro
      - ./${ZBX_AGENT_CONFIG_FILE}:/etc/zabbix/zabbix_agent2.d/${ZBX_AGENT_CONFIG_FILE}:ro
      - ../scripts/user_scripts/:/var/lib/zabbix/user_scripts/:ro
      - ./${AGENT_SUDOERS_FILE}:/etc/sudoers.d/${AGENT_SUDOERS_FILE}:ro
